export const GET_ALL_REGIONS_IN_DATA = 'GET_ALL_REGIONS_IN_DATA';
export const GET_ALL_REGIONS_IN_DATA_SUCCESS = 'GET_ALL_REGIONS_IN_DATA_SUCCESS';
export const GET_ALL_REGIONS_IN_DATA_ERROR = 'GET_ALL_REGIONS_IN_DATA_ERROR';

export const GET_POLICY_DATA_OF_REGION = 'GET_POLICY_DATA_OF_REGION';
export const GET_POLICY_DATA_OF_REGION_SUCCESS = 'GET_POLICY_DATA_OF_REGION_SUCCESS';
export const GET_POLICY_DATA_OF_REGION_ERROR = 'GET_POLICY_DATA_OF_REGION_ERROR';
export const RESET_POLICY_DATA_OF_REGION = 'RESET_POLICY_DATA_OF_REGION'; 

export const GET_POLICY_ID_DETAILS = 'GET_POLICY_ID_DETAILS';
export const GET_POLICY_ID_DETAILS_SUCCESS = 'GET_POLICY_ID_DETAILS_SUCCESS';
export const GET_POLICY_ID_DETAILS_ERROR = 'GET_POLICY_ID_DETAILS_ERROR';
export const RESET_POLICY_DETAILS = 'RESET_POLICY_DETAILS';
export const SAVE_NEW_POLICY_DETAILS = 'SAVE_NEW_POLICY_DETAILS';
export const SAVE_NEW_POLICY_DETAILS_SUCCESS = 'SAVE_NEW_POLICY_DETAILS_SUCCESS';
export const SAVE_NEW_POLICY_DETAILS_ERROR = 'SAVE_NEW_POLICY_DETAILS_ERROR';